CREATE TABLE demo (
	id BIGINT(20) NOT NULL auto_increment,
	info VARCHAR(50) NOT NULL DEFAULT '' COMMENT '内容',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
	PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT charset = utf8 COMMENT 'demo';